<?php
$ASSET_TYPES = [
    'creative' => [
        'label'  => 'Creatives',
        'icon'   => 'fa-palette',
        'color'  => '#e74c3c',
        'prefix' => 'CR',
        'extra'  => [
            'content_type'   => 'Content Type',
            'asset_type_det' => 'Asset Type',
            'format_size'    => 'Format / Size',
            'platform'       => 'Platform',
            'campaign_theme' => 'Campaign / Theme',
            'brief_desc'     => 'Brief / Description',
        ]
    ],
    'landing_page' => [
        'label'  => 'Landing Pages',
        'icon'   => 'fa-globe',
        'color'  => '#2980b9',
        'prefix' => 'LP',
        'extra'  => [
            'page_url'         => 'Page URL / Slug',
            'page_goal'        => 'Page Goal',
            'lp_type'          => 'Landing Page Type',
            'cta_text'         => 'CTA Text',
            'form_fields'      => 'Form Fields Required',
            'seo_title'        => 'SEO Title',
            'meta_description' => 'Meta Description',
            'dev_owner'        => 'Dev Owner (SS)',
            'content_writer'   => 'Content Writer',
            'utm_params'       => 'UTM Parameters',
            'ab_test'          => 'A/B Test?',
            'conversion_goal'  => 'Conversion Goal',
            'linked_creative'  => 'Linked Creative ID',
            'linked_lm'        => 'Linked Lead Magnet ID',
            'linked_email_seq' => 'Linked Email Seq ID',
        ]
    ],
    'content_writing' => [
        'label'  => 'Content Writing',
        'icon'   => 'fa-pen-nib',
        'color'  => '#27ae60',
        'prefix' => 'CW',
        'extra'  => [
            'content_format'   => 'Content Format',
            'topic'            => 'Topic / Working Title',
            'target_keywords'  => 'Target Keyword(s)',
            'word_count'       => 'Word Count (Target)',
            'audience_persona' => 'Audience Persona',
            'funnel_stage'     => 'Funnel Stage',
            'tone_of_voice'    => 'Tone of Voice',
            'draft_link'       => 'Draft Link',
            'seo_optimised'    => 'SEO Optimised?',
            'cms_published'    => 'CMS Published?',
            'linked_lp'        => 'Linked Landing Page ID',
        ]
    ],
    'lead_magnet' => [
        'label'  => 'Lead Magnets',
        'icon'   => 'fa-magnet',
        'color'  => '#8e44ad',
        'prefix' => 'LM',
        'extra'  => [
            'lm_type'         => 'Lead Magnet Type',
            'topic'           => 'Topic / Title',
            'format'          => 'Format',
            'target_persona'  => 'Target Persona',
            'funnel_stage'    => 'Funnel Stage',
            'num_pages'       => 'No. of Pages / Qs',
            'gating'          => 'Gating? (Form?)',
            'download_link'   => 'Download / Access Link',
            'lead_data_to'    => 'Lead Data Goes To',
            'results_defined' => 'Results / Outcomes Defined?',
            'content_writer'  => 'Content Writer',
            'designer'        => 'Designer',
            'linked_lp'       => 'Linked Landing Page ID',
            'linked_content'  => 'Linked Content ID',
        ]
    ],
    'email_sequence' => [
        'label'  => 'Email Sequences',
        'icon'   => 'fa-envelope',
        'color'  => '#d35400',
        'prefix' => 'EM',
        'extra'  => [
            'sequence_name'  => 'Sequence Name',
            'email_num'      => 'Email # in Sequence',
            'subject_line'   => 'Email Subject Line',
            'email_type'     => 'Email Type',
            'trigger'        => 'Trigger / Entry Point',
            'audience_seg'   => 'Audience Segment',
            'send_delay'     => 'Send Day / Delay',
            'esp_tool'       => 'ESP / Tool',
            'template_used'  => 'Template Used',
            'open_rate_tgt'  => 'Open Rate Target',
            'click_rate_tgt' => 'Click Rate Target',
            'linked_lm'      => 'Linked Lead Magnet ID',
        ]
    ],
    'ad_copy' => [
        'label'  => 'Ad Copy',
        'icon'   => 'fa-bullhorn',
        'color'  => '#c0392b',
        'prefix' => 'AC',
        'extra'  => [
            'ad_platform'    => 'Ad Platform',
            'ad_format'      => 'Ad Format',
            'ad_objective'   => 'Ad Objective',
            'headline1'      => 'Headline (H1)',
            'headline2'      => 'Headline (H2)',
            'body_copy'      => 'Body Copy',
            'cta_text'       => 'CTA Text',
            'dest_url'       => 'Destination URL',
            'audience_tgt'   => 'Audience Targeting',
            'budget'         => 'Budget (₹)',
            'run_start'      => 'Run Start Date',
            'run_end'        => 'Run End Date',
            'utm_params'     => 'UTM Parameters',
            'ad_account_id'  => 'Ad Account / Campaign ID',
            'linked_creative'=> 'Linked Creative ID',
        ]
    ],
    'seo' => [
        'label'  => 'SEO',
        'icon'   => 'fa-magnifying-glass',
        'color'  => '#16a085',
        'prefix' => 'SEO',
        'extra'  => [
            'seo_task_type'   => 'SEO Task Type',
            'target_page_url' => 'Target Page / URL',
            'primary_kw'      => 'Primary Keyword',
            'secondary_kw'    => 'Secondary Keywords',
            'current_rank'    => 'Current Ranking',
            'target_rank'     => 'Target Ranking',
            'search_vol'      => 'Monthly Search Volume',
            'kw_difficulty'   => 'Keyword Difficulty',
            'on_page_changes' => 'On-Page Changes',
            'backlink_target' => 'Backlink Target',
            'tool_used'       => 'Tool Used',
            'tracking_impl'   => 'Tracking Implemented?',
            'linked_content'  => 'Linked Content ID',
            'linked_lp'       => 'Linked LP ID',
        ]
    ],
    'webinar_event' => [
        'label'  => 'Webinars & Events',
        'icon'   => 'fa-microphone',
        'color'  => '#2c3e50',
        'prefix' => 'EV',
        'extra'  => [
            'event_type'       => 'Event Type',
            'event_format'     => 'Event Format',
            'topic'            => 'Topic / Agenda',
            'speakers'         => 'Speaker(s)',
            'registration_url' => 'Registration Link',
            'platform'         => 'Platform / Tool',
            'event_date'       => 'Event Date',
            'event_time'       => 'Event Time',
            'duration_mins'    => 'Duration (mins)',
            'expected_att'     => 'Expected Attendees',
            'actual_att'       => 'Actual Attendees',
            'recording_link'   => 'Recording Link',
            'followup_sent'    => 'Follow-Up Email Sent?',
        ]
    ],
];

$CAMPAIGN_STATUSES = ['Planning', 'Active', 'Paused', 'Completed', 'Cancelled'];
$ASSET_STATUSES    = ['Not Started', 'Briefed', 'In Progress', 'In Review', 'Approved', 'Scheduled', 'Live', 'Amends', 'On Hold', 'Cancelled', 'Archived'];
$PRIORITIES        = ['Low', 'Medium', 'High', 'Critical'];
$APPROVAL_OPTS     = ['Pending', 'Yes', 'No'];
